with LOCATION_DETAILS AS
(SELECT DISTINCT LOCATION_ISO_CODE,PROVINCE,COUNTRY,CONTINENT,ISLAND,TIME_ZONE
 FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" )
SELECT * FROM LOCATION_DETAILS