with LOCATION_STATUS AS
(SELECT DISTINCT LOCATION_ISO_CODE,SPECIAL_STATUS
 FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" 
 WHERE SPECIAL_STATUS IS  NOT NULL)
SELECT * FROM LOCATION_STATUS