with LOCATION_MEASURES AS
( SELECT LOCATION_ISO_CODE,DATE,NEW_CASES,NEW_DEATHS,NEW_RECOVERED,NEW_ACTIVE_CASES,TOTAL_CASES,
TOTAL_DEATHS,TOTAL_RECOVERED,TOTAL_ACTIVE_CASES,NEW_CASES_PER_MILLION,TOTAL_CASES_PER_MILLION,
NEW_DEATHS_PER_MILLION,TOTAL_DEATHS_PER_MILLION,CASE_FATALITY_RATE,CASE_RECOVERED_RATE,GROWTH_FACTOR_OF_NEW_CASES,
GROWTH_FACTOR_OF_NEW_DEATHS
FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" 
)
SELECT * FROM LOCATION_MEASURES