with LOCATION_LEVEL AS
(SELECT DISTINCT LOCATION_ISO_CODE,LOCATION_LEVEL AS LOC_LEVEL
 FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" )
SELECT * FROM LOCATION_LEVEL