with LOCATION_POPULATION AS
(SELECT DISTINCT LOCATION_ISO_CODE,POPULATION,POPULATION_DENSITY 
 FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" 
 )
SELECT * FROM LOCATION_POPULATION