with LOCATION_ARCHITECTURE AS
(SELECT DISTINCT LOCATION_ISO_CODE,TOTAL_REGENCIES,TOTAL_CITIES,TOTAL_DISTRICTS,TOTAL_URBAN_VILLAGES,TOTAL_RURAL_VILLAGES
 FROM "FIVETRAN_INTERVIEW_DB"."GOOGLE_SHEETS"."COVID_19_INDONESIA_SAHILPREET_SINGH" 
 )
SELECT * FROM LOCATION_ARCHITECTURE