WITH LOCATION_MERGED AS
(
    SELECT LM.LOCATION_ISO_CODE,MIN(DATE) AS FIRST_CASE_DATE,
    SUM(TOTAL_CASES) AS TOTAL_NUMBER_OF_CASES,
    SUM(TOTAL_DEATHS) AS TOTAL_NUMBER_OF_DEATHS,
    SUM(TOTAL_RECOVERED) AS TOTAL_NUMBER_OF_RECOVERED,
    SUM(TOTAL_ACTIVE_CASES) AS TOTAL_NUMBER_OF_ACTIVE_CASES,
    (SUM(TOTAL_CASES_PER_MILLION)/SUM(POPULATION))*1000000 AS CASES_PER_MILLION,
    (SUM(TOTAL_DEATHS_PER_MILLION)/SUM(POPULATION))*1000000 AS DEATHS_PER_MILLION,
    AVG(GROWTH_FACTOR_OF_NEW_CASES) AS AVERAGE_GROWTH_FACTOR_OF_NEW_CASES,
    AVG(GROWTH_FACTOR_OF_NEW_DEATHS) AS AVERAGE_GROWTH_FACTOR_OF_NEW_DEATHS,
    (SUM(TOTAL_RECOVERED)/SUM(TOTAL_CASES)) * 100 AS RECOVERY_RATE,
    (SUM(TOTAL_DEATHS)/SUM(TOTAL_CASES))* 100 AS DEATH_RATE


    FROM {{ ref('location_measures') }} LM INNER JOIN 
    {{ ref('location_population') }} LP 
    on LM.LOCATION_ISO_CODE=LP.LOCATION_ISO_CODE
    GROUP BY LM.LOCATION_ISO_CODE

)
SELECT * FROM LOCATION_MERGED